## 1 Preparación del Entorno

In [1]:
#Asegúrate de tener instalado Pandas en tu entorno de trabajo.
#Descarga el archivo dataset.csv desde Kaggle.
#Elige un dataset que te interese y que no incluya visualización de datos. Algunas sugerencias pueden ser datasets relacionados con ventas, compras, productos, etc.

In [2]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

## 2. Cargar los Datos

In [4]:
#Carga el archivo CSV en un DataFrame de Pandas.
path = "/content/drive/MyDrive/SONDA | Data Science/Data Science Fundamentals/BBDD/COVID-19 Dataset.csv"
df = pd.read_csv(path)
#Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.
df.head()

,Continent,Country,Last_Updated_Date,Total_Cases,Total_Deaths,Total_Cases_Per_Million,Total_Deaths_Per_Million,Total_tests,Positive_rate,Total_Vaccinations,People_Vaccinated,People_Fully_Vaccinated,Population,Population_Density,Median_Age,Aged_65_Older,Aged_70_Older,GDP_Per_Capita
0,Asia,Afghanistan,11-10-2021,155540.0,7228.0,3904.565,181.447,NaN,NaN,2369625.0,828601.0,NaN,39835428,54.422,18.6,2.581,1.337,1803.987
1,Europe,Albania,11-10-2021,175163.0,2777.0,60970.074,966.608,NaN,NaN,1795351.0,962281.0,833070.0,2872934,104.871,38.0,13.188,8.643,11803.431
2,Africa,Algeria,11-10-2021,204695.0,5855.0,4587.864,131.229,NaN,NaN,NaN,NaN,NaN,44616626,17.348,29.1,6.211,3.857,13913.839
3,Europe,Andorra,11-10-2021,15307.0,130.0,197882.462,1680.585,215733.0,0.054,NaN,NaN,NaN,77354,163.755,NaN,NaN,NaN,NaN
4,Africa,Angola,11-10-2021,61580.0,1629.0,1814.720,48.006,NaN,NaN,4074677.0,2863708.0,1210969.0,33933611,23.890,16.8,2.405,1.362,5819.495

## 3.Exploración Inicial de los Datos

In [10]:
#Muestra las últimas 5 filas del DataFrame.
df.tail()
#Utiliza el método info() para obtener información general sobre el DataFrame,
#incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
df.info()
#Genera estadísticas descriptivas del DataFrame utilizando el método describe().
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Continent                 214 non-null    object
 1   Country                   216 non-null    object
 2   Last_Updated_Date         216 non-null    object
 3   Total_Cases               195 non-null    float64
 4   Total_Deaths              188 non-null    float64
 5   Total_Cases_Per_Million   195 non-null    float64
 6   Total_Deaths_Per_Million  188 non-null    float64
 7   Total_tests               104 non-null    float64
 8   Positive_rate             105 non-null    float64
 9   Total_Vaccinations        199 non-null    float64
 10  People_Vaccinated         194 non-null    float64
 11  People_Fully_Vaccinated   196 non-null    float64
 12  Population                216 non-null    int64
 13  Population_Density        204 non-null    float64
 14  Median_Age                189 non-null    float64
 15  Aged_65_Older             187 non-null    float64
 16  Aged_70_Older             188 non-null    float64
 17  GDP_Per_Capita            191 non-null    float64
dtypes: float64(14), int64(1), object(3)
memory usage: 30.5+ KB

,Total_Cases,Total_Deaths,Total_Cases_Per_Million,Total_Deaths_Per_Million,Total_tests,Positive_rate,Total_Vaccinations,People_Vaccinated,People_Fully_Vaccinated,Population,Population_Density,Median_Age,Aged_65_Older,Aged_70_Older,GDP_Per_Capita
count,1.950000e+02,1.880000e+02,195.000000,188.000000,1.040000e+02,105.000000,1.990000e+02,1.940000e+02,1.960000e+02,2.160000e+02,204.000000,189.000000,187.00000,188.000000,191.000000
mean,1.497207e+06,3.161628e+04,48277.313903,847.484649,2.913921e+07,0.075267,3.608701e+07,2.099407e+07,1.566425e+07,3.925197e+07,452.729235,30.318519,8.63015,5.446511,19239.028079
std,5.801238e+06,1.132875e+05,48884.349054,934.856331,8.720517e+07,0.100351,1.799845e+08,1.010943e+08,8.127987e+07,1.465951e+08,2104.372350,9.138609,6.13073,4.172024,20563.308679
min,1.000000e+00,1.000000e+00,8.602000,3.101000,4.638000e+04,0.000000,2.911000e+03,1.502000e+03,1.409000e+03,8.120000e+02,0.137000,15.100000,1.14400,0.526000,661.240000
25%,2.152000e+04,4.160000e+02,4021.325500,89.606000,1.747248e+06,0.015000,3.208470e+05,2.288868e+05,1.577062e+05,8.639242e+05,37.047250,22.000000,3.48650,2.058000,4025.412000
50%,1.722780e+05,2.714500e+03,35656.454000,488.109000,5.172624e+06,0.046000,2.301812e+06,1.412022e+06,9.078925e+05,6.902440e+06,86.152500,29.600000,6.22400,3.845000,12236.706000
75%,6.573700e+05,1.416800e+04,81109.049000,1449.603000,2.050958e+07,0.102000,1.388632e+07,7.503862e+06,6.050455e+06,2.709629e+07,212.847000,38.700000,13.92100,8.627250,27467.146000
max,5.347403e+07,1.084066e+06,220088.970000,5986.406000,5.923819e+08,0.778000,2.222666e+09,1.154856e+09,1.047872e+09,1.444216e+09,20546.766000,48.200000,27.04900,18.493000,116935.600000

## Limpieza de Datos

In [27]:
#Identifica y maneja los datos faltantes utilizando técnicas apropiadas
 #(relleno con valores estadísticos, interpolación, eliminación, etc.).
#df["Continent"].unique() #['Asia', 'Europe', 'Africa', 'North America', 'South America','Oceania', nan]
df[df["Continent"].isnull()] # hay dos filas con contienente Nan pero al parecer el continete está ubicado en la columna Country
#se reemplazan los valores de Continent por los de Country para el caso de Country = North America y "Oceania"
df.loc[df["Country"] == "North America", "Continent"] = "North America"
df.loc[df["Country"] == "Oceania", "Continent"] = "Oceania"

In [28]:
#Corrige los tipos de datos si es necesario (por ejemplo, convertir cadenas a fechas).
#convertir Last_Updated_Date a tipo fecha datetime
df['Last_Updated_Date'] = pd.to_datetime(df['Last_Updated_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Continent                 216 non-null    object
 1   Country                   216 non-null    object
 2   Last_Updated_Date         216 non-null    datetime64[ns]
 3   Total_Cases               195 non-null    float64
 4   Total_Deaths              188 non-null    float64
 5   Total_Cases_Per_Million   195 non-null    float64
 6   Total_Deaths_Per_Million  188 non-null    float64
 7   Total_tests               104 non-null    float64
 8   Positive_rate             105 non-null    float64
 9   Total_Vaccinations        199 non-null    float64
 10  People_Vaccinated         194 non-null    float64
 11  People_Fully_Vaccinated   196 non-null    float64
 12  Population                216 non-null    int64
 13  Population_Density        204 non-null    float64
 14  Median_Age                189 non-null    float64
 15  Aged_65_Older             187 non-null    float64
 16  Aged_70_Older             188 non-null    float64
 17  GDP_Per_Capita            191 non-null    float64
dtypes: datetime64[ns](1), float64(14), int64(1), object(2)
memory usage: 30.5+ KB

In [39]:
#Elimina duplicados si los hay.
df.duplicated().value_counts() #no hay duplicados

False    216
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   continent                     216 non-null    object
 1   country                       216 non-null    object
 2   last_updated_date             216 non-null    datetime64[ns]
 3   total_cases                   195 non-null    float64
 4   total_deaths                  188 non-null    float64
 5   total_cases_per_million       195 non-null    float64
 6   total_deaths_per_million      188 non-null    float64
 7   total_tests                   104 non-null    float64
 8   positive_rate                 105 non-null    float64
 9   total_vaccinations            199 non-null    float64
 10  people_vaccinated             194 non-null    float64
 11  people_fully_vaccinated       196 non-null    float64
 12  population                    216 non-null    int64
 13  population_density            204 non-null    float64
 14  median_age                    189 non-null    float64
 15  aged_65_older                 187 non-null    float64
 16  aged_70_older                 188 non-null    float64
 17  gdp_per_capita                191 non-null    float64
 18  % de people_fully_vaccinated  196 non-null    float64
dtypes: datetime64[ns](1), float64(15), int64(1), object(2)
memory usage: 32.2+ KB

## 5. Transformación de Datos

In [ ]:
#Crea nuevas columnas basadas en operaciones con las columnas existentes
 #(por ejemplo, calcular ingresos a partir de ventas y precios).
#se crea la columna % de personas completamente vacunadas y se obtiene sobre la poblacion del pais
# se redondea a 2 decimales
df["%_de_people_fully_vaccinated"] = ((df["People_Fully_Vaccinated"] / df["Population"]) * 100).round(2)
#Normaliza o estandariza columnas si es necesario.
#como normalización se transforma el nombre de columnas a minusculas
df.columns = df.columns.str.lower()

In [92]:
#Clasifica los datos en categorías relevantes.
#Crearé la columna >1000_deaths para visualizar los paises donde el total de muertes fue superior a las 1000

df[">1000_deaths"] = df["total_deaths"].apply(lambda x: "True" if x > 1000 else "False")
df.head(20)

#categorizar un pais segun su poblacion
def cat_population(x: int):
  if x <= 500000: return "micropais"
  elif x >=500000 and x <=4999999: return "pequeño"
  elif x >= 5000000 and x <= 49999999: return "mediano"
  elif x >= 50000000 and x <= 199999999: return "grande"
  elif x >= 200000000: return "muy grande"
#se categoriza tamaño de la poblacion del pais
df["categoria_poblacion"] = df["population"].apply(lambda x:cat_population(x) )
#confirmar si se aplico correctamente la funcion y se visualiza la nueva columna
df[df["country"]=="China"] #poblacion 1444216102	correspondería a gigante
df.head()

,continent,country,last_updated_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_tests,positive_rate,total_vaccinations,...,people_fully_vaccinated,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,% de people_fully_vaccinated,>1000_deaths,categoria_poblacion
40,Asia,China,2021-11-10,96512.0,4636.0,66.827,3.21,NaN,NaN,2.222666e+09,...,1.047872e+09,1444216102,147.674,38.7,10.641,5.929,15308.712,72.56,True,muy grande

## 6. Análisis de Datos

In [57]:
#Realiza agrupaciones de datos utilizando groupby para obtener insights específicos
 #(por ejemplo, ventas por producto, ventas por región, etc.).
 #Aplica funciones de agregación como sum, mean, count, min, max, std, y var.

# variabilidad de las muertes totales por país dentro de cada continente.
#oceania tiene una desviacion std relativamente baja (respecto a los otros continentes)
#lo que significa que la cantidad de muertes es similar en sus paises
df.groupby("continent")["total_deaths"].std()

#se visualiza la poblacion total y la poblacion completamnete vacunada de cada continente existente en el dataset
df.groupby("continent")[["population", "people_fully_vaccinated"]].sum()

#se visualiza la poblacion total y la poblacion completamnete vacunada agrupada por continente y pais
df.groupby(["continent", "country"])[["population", "people_fully_vaccinated"]].sum()

#se visualiza la poblacion total, la poblacion completamnete vacunada y el total de casos covid agrupada por continente y pais
df.groupby("continent")[["population", "people_fully_vaccinated", "total_cases"]].sum()

#se visualiza la poblacion total , la poblacion completamnete vacunada, el total de casos y total de muertes agrupada por continente y pais
df.groupby(["continent", "country"])[["population", "people_fully_vaccinated", "total_cases","total_deaths"]].sum()

               population  people_fully_vaccinated  total_cases
continent
Africa         1371687302             6.105508e+07    8395217.0
Asia           4646440014             1.803981e+09   77231697.0
Europe          750832184             3.986440e+08   60959340.0
North America  1189383891             5.797600e+08  106948060.0
Oceania          86130931             3.316176e+07     421440.0
South America   433950159             1.935908e+08   37999617.0

In [63]:
#Utiliza el método apply para realizar operaciones más complejas y personalizadas.
#porcentaje de muertes
#se obtiene % de muertes sobre total de casos de covid, en caso de que se cumpla la condicion de que total_cases sea >0. sino, se completa con 0.
#se visualiza agrupado con contiente y pais
df.groupby(["continent", "country"]).apply(lambda x: ( x["total_deaths"].sum() / x["total_cases"].sum()) * 100 if x["total_cases"].sum() > 0 else 0)

<ipython-input-63-759e8cbab469>:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["continent", "country"]).apply(lambda x: ( x["total_deaths"].sum() / x["total_cases"].sum()) * 100 if x["total_cases"].sum() > 0 else 0)

continent      country
Africa         Algeria         2.860353
               Angola          2.645339
               Benin           0.653380
               Botswana        1.313648
               Burkina Faso    1.343345
                                 ...
South America  Paraguay        3.521592
               Peru            9.141081
               Suriname        2.184806
               Uruguay         1.554413
               Venezuela       1.204675
Length: 216, dtype: float64